//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapInvoker.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int AgeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceCalculatorSoap")]
    public interface WebServiceCalculatorSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SoapInvoker.ServiceReference1.HelloWorldResponse HelloWorld(SoapInvoker.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapInvoker.ServiceReference1.HelloWorldResponse> HelloWorldAsync(SoapInvoker.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int FirstNumber, int SecondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int FirstNumber, int SecondNumber);
        
        // CODEGEN: Generating message contract since element name person from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePersonDetails", ReplyAction="*")]
        SoapInvoker.ServiceReference1.SavePersonDetailsResponse SavePersonDetails(SoapInvoker.ServiceReference1.SavePersonDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePersonDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapInvoker.ServiceReference1.SavePersonDetailsResponse> SavePersonDetailsAsync(SoapInvoker.ServiceReference1.SavePersonDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SoapInvoker.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SoapInvoker.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SoapInvoker.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SoapInvoker.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SavePersonDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SavePersonDetails", Namespace="http://tempuri.org/", Order=0)]
        public SoapInvoker.ServiceReference1.SavePersonDetailsRequestBody Body;
        
        public SavePersonDetailsRequest() {
        }
        
        public SavePersonDetailsRequest(SoapInvoker.ServiceReference1.SavePersonDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SavePersonDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoapInvoker.ServiceReference1.Person person;
        
        public SavePersonDetailsRequestBody() {
        }
        
        public SavePersonDetailsRequestBody(SoapInvoker.ServiceReference1.Person person) {
            this.person = person;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SavePersonDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SavePersonDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SoapInvoker.ServiceReference1.SavePersonDetailsResponseBody Body;
        
        public SavePersonDetailsResponse() {
        }
        
        public SavePersonDetailsResponse(SoapInvoker.ServiceReference1.SavePersonDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SavePersonDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SavePersonDetailsResult;
        
        public SavePersonDetailsResponseBody() {
        }
        
        public SavePersonDetailsResponseBody(string SavePersonDetailsResult) {
            this.SavePersonDetailsResult = SavePersonDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceCalculatorSoapChannel : SoapInvoker.ServiceReference1.WebServiceCalculatorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceCalculatorSoapClient : System.ServiceModel.ClientBase<SoapInvoker.ServiceReference1.WebServiceCalculatorSoap>, SoapInvoker.ServiceReference1.WebServiceCalculatorSoap {
        
        public WebServiceCalculatorSoapClient() {
        }
        
        public WebServiceCalculatorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceCalculatorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCalculatorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCalculatorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapInvoker.ServiceReference1.HelloWorldResponse SoapInvoker.ServiceReference1.WebServiceCalculatorSoap.HelloWorld(SoapInvoker.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SoapInvoker.ServiceReference1.HelloWorldRequest inValue = new SoapInvoker.ServiceReference1.HelloWorldRequest();
            inValue.Body = new SoapInvoker.ServiceReference1.HelloWorldRequestBody();
            SoapInvoker.ServiceReference1.HelloWorldResponse retVal = ((SoapInvoker.ServiceReference1.WebServiceCalculatorSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapInvoker.ServiceReference1.HelloWorldResponse> SoapInvoker.ServiceReference1.WebServiceCalculatorSoap.HelloWorldAsync(SoapInvoker.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapInvoker.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            SoapInvoker.ServiceReference1.HelloWorldRequest inValue = new SoapInvoker.ServiceReference1.HelloWorldRequest();
            inValue.Body = new SoapInvoker.ServiceReference1.HelloWorldRequestBody();
            return ((SoapInvoker.ServiceReference1.WebServiceCalculatorSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Add(int FirstNumber, int SecondNumber) {
            return base.Channel.Add(FirstNumber, SecondNumber);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int FirstNumber, int SecondNumber) {
            return base.Channel.AddAsync(FirstNumber, SecondNumber);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapInvoker.ServiceReference1.SavePersonDetailsResponse SoapInvoker.ServiceReference1.WebServiceCalculatorSoap.SavePersonDetails(SoapInvoker.ServiceReference1.SavePersonDetailsRequest request) {
            return base.Channel.SavePersonDetails(request);
        }
        
        public string SavePersonDetails(SoapInvoker.ServiceReference1.Person person) {
            SoapInvoker.ServiceReference1.SavePersonDetailsRequest inValue = new SoapInvoker.ServiceReference1.SavePersonDetailsRequest();
            inValue.Body = new SoapInvoker.ServiceReference1.SavePersonDetailsRequestBody();
            inValue.Body.person = person;
            SoapInvoker.ServiceReference1.SavePersonDetailsResponse retVal = ((SoapInvoker.ServiceReference1.WebServiceCalculatorSoap)(this)).SavePersonDetails(inValue);
            return retVal.Body.SavePersonDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapInvoker.ServiceReference1.SavePersonDetailsResponse> SoapInvoker.ServiceReference1.WebServiceCalculatorSoap.SavePersonDetailsAsync(SoapInvoker.ServiceReference1.SavePersonDetailsRequest request) {
            return base.Channel.SavePersonDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapInvoker.ServiceReference1.SavePersonDetailsResponse> SavePersonDetailsAsync(SoapInvoker.ServiceReference1.Person person) {
            SoapInvoker.ServiceReference1.SavePersonDetailsRequest inValue = new SoapInvoker.ServiceReference1.SavePersonDetailsRequest();
            inValue.Body = new SoapInvoker.ServiceReference1.SavePersonDetailsRequestBody();
            inValue.Body.person = person;
            return ((SoapInvoker.ServiceReference1.WebServiceCalculatorSoap)(this)).SavePersonDetailsAsync(inValue);
        }
    }
}
